---
title: "Get annotated, differentially-methylated regions by comparing samples from two conditions"
author: "Tsunghan Hsieh"
description: >
  This file demonstrates how to get annotated DMR.
date: "`r format(Sys.Date(), format='%d-%m-%Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clustering_Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set RMarkDown options
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE, eval = TRUE, collapse = FALSE)

# Turn off scientific notation
options(scipen = 999)

# load all functions
devtools::document()
devtools::load_all()
```

# Get adjusted methylation counts
***
We first get the methylation counts for each sample.

```{r todo}
# Run the following Rmd file:
# ./Doc/getUnadjustedMethylationCount2018.rmd.
# ./Doc/getUnadjustedMethylationCount2022.rmd.
```

# Set-up
***

## Load libraries
```{r library}
library(dplyr)
library(methylKit)
library(here)
library(stringr)
```

## Set dir
***
Set input and output dir.

```{r dir}
sampleSheetDir <- here::here("Doc","sampleSheet")
dmrDir <- here::here("Results", "Statistics", "DMR")
annotatedDmrDir <- here::here("Results", "Statistics", "DMR_annotated")
```

# TODO: Get DMR
***
Get DMR for 5hmc + 5mc, 5hmc, and 5mc. For more information, check `./Doc/getDMR_2018.Rmd` and `getDMR_2022.Rmd`

```{r DMR}

```

# Get annotated DMR
Get annotated DMR for 5hmc + 5mc, 5hmc, and 5mc.
```{r annotated_DMR}
dmrList <- list.files(dmrDir)

## Annotate CpG islands
for (file in dmrList) {
  outputfname <- sub(".*/([^.]+)\\.csv", "\\1", file)
  outputfname <- paste0("cpg_annotated_", outputfname)
  outputdir <- here::here("Results/Statistics/DMR_annotated/")
  output <- here::here(outputdir, outputfname)
  
  annotateDMR(
    input = here::here(dmrDir,file),
    col_names = c("chr", "start", "end", "strand"),
    annots = c("mm10_cpg_islands", "mm10_cpg_shores","mm10_cpg_shelves", "mm10_cpg_inter"),
    output = output)
}

## Annotate basic genes
## Could be longer than CpG annotation
for (file in dmrList) {
  outputfname <- sub(".*/([^.]+)\\.csv", "\\1", file)
  outputfname <- paste0("genes_annotated_", outputfname)
  outputdir <- here::here("Results/Statistics/DMR_annotated/")
  output <- here::here(outputdir, outputfname)
  
  annotateDMR(
    input = here::here(dmrDir,file),
    col_names = c("chr", "start", "end", "strand"),
    annots = c("mm10_basicgenes"),
    output = output)
}
```

# Overview 
***
Some over analysis for the total dmr

```{r overview_cpg}
# Total number of DMR
cpg_list <- list()
for (file in list.files(annotatedDmrDir)) {
  dmr_fname <- unlist(strsplit(file, "_"))
}

cpg_annotated_DMR_5hmc_2018_SI_3
```
