---
title: "Get adjusted methylation count from Bismark methylation extraction files"
author: "Tsunghan Hsieh"
description: >
  This file demonstrates how to get methylation count from the bismark summary file.
date: "`r format(Sys.Date(), format='%d-%m-%Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Clustering_Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
# Set RMarkDown options
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE, eval = TRUE, collapse = FALSE)

# Turn off scientific notation
options(scipen = 999)

```

# TODO
***
```{r todo}
# Run the following Rmd file:
# ./Doc/getUnadjustedMethylationCount2022.rmd.
```

# Set-up
***

## Load libraries
```{r library}
library(dplyr)
library(methylKit)
library(here)
library(stringr)
```

## Set dir
***
Set input and output dir.

```{r dir}
sampleSheetDir <- here::here("Doc","sampleSheet")
inputTmpDir <- here::here("Results", "Tmp")
outputTmpDir <- here::here("Results", "Tmp")
```

## Set global variable
***
Set global variable
```{r GLOBAL}
YEAR <- 2022
TISSUE <- "LI"
```

# Load and arrange the data
## Sample file
***
Read sample file.

```{r sample_file}
# Sample sheet list ====
sampleSheet <- read.csv(file.path(inputTmpDir, paste0("RRBS_", YEAR, "_", TISSUE, "_sampleSheet_",".csv")))
sampleSheet  <- sampleSheet [,2:ncol(sampleSheet)]

sampleSheetTotal <- sampleSheet |>
  dplyr::filter(OX == "-") |>
  dplyr::mutate(fpath = file.path(outputTmpDir,paste0(paste0(index,"_total.csv"))))

sampleSheet5hmc <- sampleSheet |>
  dplyr::filter(OX == "+") |>
  dplyr::mutate(fpath = file.path(outputTmpDir,paste0(paste0(index,"_5hmc.csv"))))

sampleSheet5mc <- sampleSheet |>
  dplyr::filter(OX == "+") |>
  dplyr::mutate(fpath = file.path(outputTmpDir,paste0(paste0(index,"_5mc.csv"))))

# Read methylation call list (tile = 100) ====
tile <- readRDS(file.path(inputTmpDir, paste0("RRBS_", YEAR, "_", TISSUE, "_methTile100_", ".rds")))

# Confirm the sample ID and sampleSheet
sampleIdList <- getSampleID(tile)
for (i in 1:length(sampleIdList)) {
  if (sampleIdList[i] == sampleSheet[i,]$index)
    print("TRUE")
}
```

# Get methylation count 
***
Get the methylation counts for 5hmc + 5mc, 5hmc, and 5mc.

```{r methylation}
# Get 5hmc+5mc subset ====
# 2018: c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24)
# 2022: c(7, 8, 9, 10, 11, 12)
for (i in c(7, 8, 9, 10, 11, 12)) {
  sampleID <- sampleIdList[i]
  tile[[i]]$freqC <- 100*(tile[[i]]$numCs/tile[[i]]$coverage)
  write.csv(tile[[i]], file.path(outputTmpDir,paste0(sampleID,"_total.csv")),row.names=FALSE,quote=FALSE)
}
remove(i, sampleID)

# Get 5hmc subset ====
# 2018: c(1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23)
# 2022: c(1, 2, 3, 4, 5, 6)
for (i in c(1, 2, 3, 4, 5, 6)) {
  sampleID <- sampleIdList[i]
  tile[[i]]$freqC <- 100*(tile[[i]]$numCs/tile[[i]]$coverage)
  write.csv(tile[[i]], file.path(outputTmpDir,paste0(sampleID,"_5hmc.csv")),row.names=FALSE,quote=FALSE)
}
remove(i, sampleID)

# Get 5mc subset ====
# 2018: c(1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23)
# 2022: c(1, 2, 3, 4, 5, 6)
for (i in c(1, 2, 3, 4, 5, 6)) {
  sampleID <- sampleIdList[i]
  
  # 2018: realMc <- methylKit::adjustMethylC(mc = tile[[i+1]], hmc = tile[[i]])
  # 2022: realMc <- methylKit::adjustMethylC(mc = tile[[i+6]], hmc = tile[[i]])
  realMc <- methylKit::adjustMethylC(mc = tile[[i+6]], hmc = tile[[i]])
  realMc$freqC <- 100*(realMc$numCs/realMc$coverage)
  write.csv(realMc, file.path(outputTmpDir,paste0(sampleID,"_5mc.csv")),row.names=FALSE,quote=FALSE)
}
remove(i, sampleID, realMc)
```
